# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/doluwamu.kaye/Downloads/Nexys-A7-100T-Master.xdc

# Block Designs: bd/Linux_bd/Linux_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd || ORIG_REF_NAME==Linux_bd} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_mig_7series_0_0/Linux_bd_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_mig_7series_0_0 || ORIG_REF_NAME==Linux_bd_mig_7series_0_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_microblaze_0_0/Linux_bd_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_microblaze_0_0 || ORIG_REF_NAME==Linux_bd_microblaze_0_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_axi_smc_0/Linux_bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_axi_smc_0 || ORIG_REF_NAME==Linux_bd_axi_smc_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_rst_mig_7series_0_81M_0/Linux_bd_rst_mig_7series_0_81M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_rst_mig_7series_0_81M_0 || ORIG_REF_NAME==Linux_bd_rst_mig_7series_0_81M_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_dlmb_v10_0/Linux_bd_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_dlmb_v10_0 || ORIG_REF_NAME==Linux_bd_dlmb_v10_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_ilmb_v10_0/Linux_bd_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_ilmb_v10_0 || ORIG_REF_NAME==Linux_bd_ilmb_v10_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_dlmb_bram_if_cntlr_0/Linux_bd_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Linux_bd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_ilmb_bram_if_cntlr_0/Linux_bd_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Linux_bd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_lmb_bram_0/Linux_bd_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_lmb_bram_0 || ORIG_REF_NAME==Linux_bd_lmb_bram_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_xbar_0/Linux_bd_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_xbar_0 || ORIG_REF_NAME==Linux_bd_xbar_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_microblaze_0_axi_periph_0/Linux_bd_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Linux_bd_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_microblaze_0_axi_intc_0/Linux_bd_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_microblaze_0_axi_intc_0 || ORIG_REF_NAME==Linux_bd_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_microblaze_0_xlconcat_0/Linux_bd_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_microblaze_0_xlconcat_0 || ORIG_REF_NAME==Linux_bd_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_mdm_1_0/Linux_bd_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_mdm_1_0 || ORIG_REF_NAME==Linux_bd_mdm_1_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_axi_gpio_0_0/Linux_bd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_axi_gpio_0_0 || ORIG_REF_NAME==Linux_bd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_axi_gpio_0_1/Linux_bd_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_axi_gpio_0_1 || ORIG_REF_NAME==Linux_bd_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_axi_quad_spi_0_0/Linux_bd_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_axi_quad_spi_0_0 || ORIG_REF_NAME==Linux_bd_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_axi_gpio_0_2/Linux_bd_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_axi_gpio_0_2 || ORIG_REF_NAME==Linux_bd_axi_gpio_0_2} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_axi_gpio_0_3/Linux_bd_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_axi_gpio_0_3 || ORIG_REF_NAME==Linux_bd_axi_gpio_0_3} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_axi_gpio_0_4/Linux_bd_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_axi_gpio_0_4 || ORIG_REF_NAME==Linux_bd_axi_gpio_0_4} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_axi_gpio_0_5/Linux_bd_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_axi_gpio_0_5 || ORIG_REF_NAME==Linux_bd_axi_gpio_0_5} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_axi_iic_0_0/Linux_bd_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_axi_iic_0_0 || ORIG_REF_NAME==Linux_bd_axi_iic_0_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_axi_uartlite_0_0/Linux_bd_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_axi_uartlite_0_0 || ORIG_REF_NAME==Linux_bd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/Linux_bd/ip/Linux_bd_axi_timer_0_0/Linux_bd_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Linux_bd_axi_timer_0_0 || ORIG_REF_NAME==Linux_bd_axi_timer_0_0} -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Linux_Hw/Linux_Hw.gen/sources_1/bd/Linux_bd/Linux_bd_ooc.xdc
