# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Linux_Hw/Linux_Hw.srcs/sources_1/bd/Linux_bd/ip/Linux_bd_axi_quad_spi_0_0/Linux_bd_axi_quad_spi_0_0.xci
# IP: The module: 'Linux_bd_axi_quad_spi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Linux_Hw/Linux_Hw.gen/sources_1/bd/Linux_bd/ip/Linux_bd_axi_quad_spi_0_0/Linux_bd_axi_quad_spi_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Linux_bd_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Linux_Hw/Linux_Hw.gen/sources_1/bd/Linux_bd/ip/Linux_bd_axi_quad_spi_0_0/Linux_bd_axi_quad_spi_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Linux_bd_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Linux_Hw/Linux_Hw.gen/sources_1/bd/Linux_bd/ip/Linux_bd_axi_quad_spi_0_0/Linux_bd_axi_quad_spi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Linux_bd_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Linux_Hw/Linux_Hw.gen/sources_1/bd/Linux_bd/ip/Linux_bd_axi_quad_spi_0_0/Linux_bd_axi_quad_spi_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Linux_bd_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Linux_Hw/Linux_Hw.srcs/sources_1/bd/Linux_bd/ip/Linux_bd_axi_quad_spi_0_0/Linux_bd_axi_quad_spi_0_0.xci
# IP: The module: 'Linux_bd_axi_quad_spi_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Linux_Hw/Linux_Hw.gen/sources_1/bd/Linux_bd/ip/Linux_bd_axi_quad_spi_0_0/Linux_bd_axi_quad_spi_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Linux_bd_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Linux_Hw/Linux_Hw.gen/sources_1/bd/Linux_bd/ip/Linux_bd_axi_quad_spi_0_0/Linux_bd_axi_quad_spi_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Linux_bd_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Linux_Hw/Linux_Hw.gen/sources_1/bd/Linux_bd/ip/Linux_bd_axi_quad_spi_0_0/Linux_bd_axi_quad_spi_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Linux_bd_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Linux_Hw/Linux_Hw.gen/sources_1/bd/Linux_bd/ip/Linux_bd_axi_quad_spi_0_0/Linux_bd_axi_quad_spi_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'Linux_bd_axi_quad_spi_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
