# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/doluwamu.kaye/Downloads/Nexys-A7-100T-Master.xdc

# Block Designs: bd/PWM_test/PWM_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test || ORIG_REF_NAME==PWM_test} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_mig_7series_0_1/PWM_test_mig_7series_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_mig_7series_0_1 || ORIG_REF_NAME==PWM_test_mig_7series_0_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_axi_uartlite_0_0/PWM_test_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_axi_uartlite_0_0 || ORIG_REF_NAME==PWM_test_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_axi_gpio_0_5/PWM_test_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_axi_gpio_0_5 || ORIG_REF_NAME==PWM_test_axi_gpio_0_5} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_microblaze_0_2/PWM_test_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_microblaze_0_2 || ORIG_REF_NAME==PWM_test_microblaze_0_2} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_dlmb_v10_1/PWM_test_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_dlmb_v10_1 || ORIG_REF_NAME==PWM_test_dlmb_v10_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_ilmb_v10_1/PWM_test_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_ilmb_v10_1 || ORIG_REF_NAME==PWM_test_ilmb_v10_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_dlmb_bram_if_cntlr_1/PWM_test_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==PWM_test_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_ilmb_bram_if_cntlr_1/PWM_test_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==PWM_test_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_lmb_bram_1/PWM_test_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_lmb_bram_1 || ORIG_REF_NAME==PWM_test_lmb_bram_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_xbar_1/PWM_test_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_xbar_1 || ORIG_REF_NAME==PWM_test_xbar_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_microblaze_0_axi_periph_1/PWM_test_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_microblaze_0_axi_periph_1 || ORIG_REF_NAME==PWM_test_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_microblaze_0_axi_intc_1/PWM_test_microblaze_0_axi_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_microblaze_0_axi_intc_1 || ORIG_REF_NAME==PWM_test_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_microblaze_0_xlconcat_1/PWM_test_microblaze_0_xlconcat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_microblaze_0_xlconcat_1 || ORIG_REF_NAME==PWM_test_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_mdm_1_1/PWM_test_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_mdm_1_1 || ORIG_REF_NAME==PWM_test_mdm_1_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_rst_mig_7series_0_81M_1/PWM_test_rst_mig_7series_0_81M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_rst_mig_7series_0_81M_1 || ORIG_REF_NAME==PWM_test_rst_mig_7series_0_81M_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_PMW_0_2/PWM_test_PMW_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_PMW_0_2 || ORIG_REF_NAME==PWM_test_PMW_0_2} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_axi_gpio_0_6/PWM_test_axi_gpio_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_axi_gpio_0_6 || ORIG_REF_NAME==PWM_test_axi_gpio_0_6} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_axi_gpio_1_0/PWM_test_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_axi_gpio_1_0 || ORIG_REF_NAME==PWM_test_axi_gpio_1_0} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_pc_6/PWM_test_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_pc_6 || ORIG_REF_NAME==PWM_test_auto_pc_6} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_us_0/PWM_test_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_us_0 || ORIG_REF_NAME==PWM_test_auto_us_0} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_us_1/PWM_test_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_us_1 || ORIG_REF_NAME==PWM_test_auto_us_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_us_2/PWM_test_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_us_2 || ORIG_REF_NAME==PWM_test_auto_us_2} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_ds_0/PWM_test_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_ds_0 || ORIG_REF_NAME==PWM_test_auto_ds_0} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_pc_0/PWM_test_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_pc_0 || ORIG_REF_NAME==PWM_test_auto_pc_0} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_ds_1/PWM_test_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_ds_1 || ORIG_REF_NAME==PWM_test_auto_ds_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_pc_1/PWM_test_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_pc_1 || ORIG_REF_NAME==PWM_test_auto_pc_1} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_ds_2/PWM_test_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_ds_2 || ORIG_REF_NAME==PWM_test_auto_ds_2} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_pc_2/PWM_test_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_pc_2 || ORIG_REF_NAME==PWM_test_auto_pc_2} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_ds_3/PWM_test_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_ds_3 || ORIG_REF_NAME==PWM_test_auto_ds_3} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_pc_3/PWM_test_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_pc_3 || ORIG_REF_NAME==PWM_test_auto_pc_3} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_ds_4/PWM_test_auto_ds_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_ds_4 || ORIG_REF_NAME==PWM_test_auto_ds_4} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_pc_4/PWM_test_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_pc_4 || ORIG_REF_NAME==PWM_test_auto_pc_4} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_ds_5/PWM_test_auto_ds_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_ds_5 || ORIG_REF_NAME==PWM_test_auto_ds_5} -quiet] -quiet

# IP: bd/PWM_test/ip/PWM_test_auto_pc_5/PWM_test_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PWM_test_auto_pc_5 || ORIG_REF_NAME==PWM_test_auto_pc_5} -quiet] -quiet

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Lab7_CustomIP/Lab7_CustomIP.gen/sources_1/bd/PWM_test/PWM_test_ooc.xdc
