# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Lab7_CustomIP/Lab7_CustomIP.srcs/sources_1/bd/PWM_test/ip/PWM_test_ilmb_bram_if_cntlr_1/PWM_test_ilmb_bram_if_cntlr_1.xci
# IP: The module: 'PWM_test_ilmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Lab7_CustomIP/Lab7_CustomIP.gen/sources_1/bd/PWM_test/ip/PWM_test_ilmb_bram_if_cntlr_1/PWM_test_ilmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_test_ilmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Lab7_CustomIP/Lab7_CustomIP.srcs/sources_1/bd/PWM_test/ip/PWM_test_ilmb_bram_if_cntlr_1/PWM_test_ilmb_bram_if_cntlr_1.xci
# IP: The module: 'PWM_test_ilmb_bram_if_cntlr_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/doluwamu.kaye/Documents/GitHub/Linux_Microblaze_V1.0/Lab7_CustomIP/Lab7_CustomIP.gen/sources_1/bd/PWM_test/ip/PWM_test_ilmb_bram_if_cntlr_1/PWM_test_ilmb_bram_if_cntlr_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PWM_test_ilmb_bram_if_cntlr_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
